export COSMOS_MONIKER="stanisloe | 2pilot" && \
export COSMOS_WALLET="wallet" && \
export COSMOS_WEBSITE="https://2pilot.dev" && \
export COSMOS_IDENTITY="8E102EA8D78D6769" && \
export COSMOS_DETAILS="Your trusted staking co-pilot" && \
export COSMOS_SECURITY_CONTACT="help@2pilot.dev" && \
export COSMOS_PROFILE_FILE_NAME="" && \
export COSMOS_NODE_ID="" && \
export COSMOS_BINARY="" && \
export COSMOS_CHAIN="" && \
export COSMOS_VALOPER="" && \
export COSMOS_WALLET_ADDRESS="" && \
export COSMOS_NODE_FOLDER="" && \
export COSMOS_NODE_BINARY_URL="" && \
export COSMOS_NODE_REPOSITORY_URL="" && \
export COSMOS_NODE_GIT_BRANCH="" && \
export COSMOS_NODE_GIT_TAG="" && \
export COSMOS_PEERS="" && \
export COSMOS_SEEDS="" && \
export COSMOS_TOKEN="" && \
export COSMOS_FEE="" && \
export COSMOS_GENESIS_URL="" && \
export COSMOS_ADDRBOOK_URL="" && \
export COSMOS_SERVICE_NAME="" && \
export COSMOS_STATE_SYNC_RPC=""